database:
  url: "jdbc:mysql://localhost:3306/yourdatabase"
  username: "root"
  password: "password"
  type: "mysql"

server:
  name: "developement"
  menu:
    items:
      - "developement"


messages:
  ask_submitted: "&aYour ask has been submitted."
  report_submitted: "&aYour report has been submitted."
  claim_success: "&aSuccessfully claimed the %type%."
  claim_failed: "&cFailed to claim the %type% or it has already been claimed."
  close_success: "&aSuccessfully closed the %type%."
  close_failed: "&cFailed to close the %type% or it has not been claimed."
  react_success: "&aMessage sent to the player."
  react_failed: "&cFailed to send message."
