name: AsteroSupport
version: '${project.version}'
main: nl.infinityastro.astrosupport.AsteroSupport
api-version: '1.20'
commands:
  ask:
    description: Submit an ask request
    usage: /ask <question>
    permission: astrosupport.use
  report:
    description: Submit a report
    usage: /report <player> <reason>
    permission: astrosupport.use
  support:
    description: Staff support commands
    usage: /support
    permission: astrosupport.staff
permissions:
  astrosupport.use:
    description: Allows the use of /ask and /report
    default: true
  astrosupport.staff:
    description: Allows staff to manage asks and reports
    default: op
  astrosupport.staff.global:
    description: Allows staff to handle global asks and reports
    default: op
